version: "3.1"
services:
  frontend:
    build: ./frontend
    
  backend:
    build: ./backend
    ports:
      - "4000/4000"

  nginx:
    build: ./nginx
    ports:
      - "8000/80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf